[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "pixels-crossfont"
version = "0.1.0"

[dependencies]
crossfont = "0.2.0"
pixels = "0.2.0"
winit = "0.24.0"

[profile.dev]
opt-level = 3
